# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b09ef80b08984c08ed686bd7e07d55eda3d3751ce7d440d8b60e5e2ecbe6d684bd2e50c3faf6deef7aa87098a16298026fd49ea6b641f9cf06ce69cf95cdbb77

test:
  secret_key_base: 4a8e4a0329c0ed887c653a5b009886e0e865f1365583417202e7c197a6b3392114e87afe99f08e8bddb9defca7de1a26b45e1d1f9856ff1981e1ed6e5cb1faac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
